extends:
  - next/core-web-vitals
  - "plugin:@typescript-eslint/recommended"
plugins:
  - "@typescript-eslint"
parser: "@typescript-eslint/parser"
rules:
  "@typescript-eslint/ban-ts-comment":
    - off
  "@typescript-eslint/member-delimiter-style":
    - error
    - multiline:
        delimiter: none
  "@typescript-eslint/semi":
    - error
    - never
  indent:
    - error
    - tab
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - off
root: true
