name: boilerplate

services:
  app:
    image: node:latest
    working_dir: /var/app
    command: ["yarn", "docker-dev"]
    environment:
      # Startup Config
      NODE_ENV: "development"
      APP_PORT: "3000"
      FONTAWESOME_TOKEN: "${FONTAWESOME_TOKEN}"
      # Public Config
      # Server Config
    volumes:
      - ./public:/var/app/public:cached
      - ./server:/var/app/server:cached
      - ./src:/var/app/src:cached
      - ./next.config.js:/var/app/next.config.js:cached
      - ./postcss.config.js:/var/app/postcss.config.js:cached
      - ./tailwind.config.js:/var/app/tailwind.config.js:cached
      - ./package.json:/var/app/package.json:cached
      - ./tsconfig.json:/var/app/tsconfig.json:cached
      - ./next-env.d.ts:/var/app/next-env.d.ts:cached
      - ./.npmrc:/var/app/.npmrc:cached
      - app-node-modules:/var/app/node_modules
    ports:
      - "${NEXT_APP_PORT:-3000}:3000"
      - "${NEXT_APP_DEBUG_PORT:-9230}:9229"

volumes:
  app-node-modules: {}
